### ISSUE TITLE
条件编译作用于import的时候可能有点问题

### ISSUE THREAD

**Issue by kanfashidoufu** [KeJunMao/vite-plugin-conditional-compile#13]
例如 
```javascript
// #v-ifdef VITE_APP_NAME='TEST'
import xxx from 'xxx'
// #v-endif
```
dev启动的时候没有这个文件的一端会报错，但是不影响代码运行，请教一下可能是什么问题

**Comment by KeJunMao** [comment]
没太懂，意思是虽然不影响运行，但是会有无法 resolve 到 xxx 的 error 吗？

请提供更多日志或者提供复现仓库

**Comment by kanfashidoufu** [comment]
报错信息如下

✘ [ERROR] [plugin vite:dep-scan] ENOENT: no such file or directory, open '/Users/wangning/Documents/qtshe/qtb-monorepo-cloud/packages/qtb-cloud/src/views/im/module/libs/util.js'

    ../../node_modules/esbuild/lib/main.js:993:33:
      993 │ ...  let result = await callback2({
          ╵                         ^

    at Object.openSync (fs.js:498:3)
    at Object.readFileSync (fs.js:394:35)
    at file:///Users/wangning/Documents/qtshe/qtb-monorepo-cloud/node_modules/vite/dist/node/chunks/dep-561c5231.js:36048:37
    at callback (/Users/wangning/Documents/qtshe/qtb-monorepo-cloud/node_modules/esbuild/lib/main.js:993:34)
    at handleRequest (/Users/wangning/Documents/qtshe/qtb-monorepo-cloud/node_modules/esbuild/lib/main.js:721:36)
    at handleIncomingPacket (/Users/wangning/Documents/qtshe/qtb-monorepo-cloud/node_modules/esbuild/lib/main.js:768:7)
    at Socket.readFromStdout (/Users/wangning/Documents/qtshe/qtb-monorepo-cloud/node_modules/esbuild/lib/main.js:644:7)
    at Socket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:293:12)
    at readableAddChunk (internal/streams/readable.js:267:9)
    at Socket.Readable.push (internal/streams/readable.js:206:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)

  This error came from the "onLoad" callback
  registered here:

    ../../node_modules/esbuild/lib/main.js:855:22:
      855 │         let promise = setup({
          ╵                       ^

    at setup (file:///Users/wangning/Documents/qtshe/qtb-monorepo-cloud/node_modules/vite/dist/node/chunks/dep-561c5231.js:36044:19)
    at handlePlugins (/Users/wangning/Documents/qtshe/qtb-monorepo-cloud/node_modules/esbuild/lib/main.js:855:23)
    at Object.buildOrServe (/Users/wangning/Documents/qtshe/qtb-monorepo-cloud/node_modules/esbuild/lib/main.js:1149:7)
    at /Users/wangning/Documents/qtshe/qtb-monorepo-cloud/node_modules/esbuild/lib/main.js:2110:17
    at new Promise (<anonymous>)
    at Object.build (/Users/wangning/Documents/qtshe/qtb-monorepo-cloud/node_modules/esbuild/lib/main.js:2109:14)
    at build (/Users/wangning/Documents/qtshe/qtb-monorepo-cloud/node_modules/esbuild/lib/main.js:1956:51)
    at file:///Users/wangning/Documents/qtshe/qtb-monorepo-cloud/node_modules/vite/dist/node/chunks/dep-561c5231.js:35748:46
    at Array.map (<anonymous>)
    at scanImports (file:///Users/wangning/Documents/qtshe/qtb-monorepo-cloud/node_modules/vite/dist/node/chunks/dep-561c5231.js:35748:31)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async discoverProjectDependencies (file:///Users/wangning/Documents/qtshe/qtb-monorepo-cloud/node_modules/vite/dist/node/chunks/dep-561c5231.js:36756:31)
    at async Timeout._onTimeout (file:///Users/wangning/Documents/qtshe/qtb-monorepo-cloud/node_modules/vite/dist/node/chunks/dep-561c5231.js:36212:34)

  The plugin "vite:dep-scan" was triggered by
  this import

    ../qtbao-pc-module/plugins/ajax/ajax.js:11:17:
      11 │ ...rom '@/views/im/module/libs/ut...
         ╵        ~~~~~~~~~~~~~~~~~~~~~~~~~~

Build failed with 1 error:
../../node_modules/esbuild/lib/main.js:993:33: ERROR: [plugin: vite:dep-scan] ENOENT: no such file or directory, open '/Users/wangning/Documents/qtshe/qtb-monorepo-cloud/packages/qtb-cloud/src/views/im/module/libs/util.js'

**Comment by kanfashidoufu** [comment]
> 没太懂，意思是虽然不影响运行，但是会有无法 resolve 到 xxx 的 error 吗？
> 
> 请提供更多日志或者提供复现仓库

我这个文件是两个项目共用的 一个需要import一个文件 另一个不需要，现在是第一次dev启动后 没有这个文件的项目会报错，后面在执行npm run dev 就不会报错了，个人感觉应该跟vite的预构建缓存有关系

**Comment by KeJunMao** [comment]
你好，我试着本地复现，但是没出现报错，如果你能提供一个最小复现仓库就好了

**Comment by kanfashidoufu** [comment]
> 你好，我试着本地复现，但是没出现报错，如果你能提供一个最小复现仓库就好了
你好 尝试了最小复现仓库
https://stackblitz.com/edit/vitejs-vite-jydaqq?file=vite.config.js
我试着复现我的场景下的报错 但是monorepo项目有点复杂 但是复现了条件编译后找不到import资源的问题 应该是同一个问题引起的
![image](https://github.com/KeJunMao/vite-plugin-conditional-compile/assets/24693561/1ec6d734-1fb8-4f09-a7e3-191754fa96ba)
使用--force 忽略缓存就可以复现 也就是为什么只有第一次才会出现报错

**Comment by kanfashidoufu** [comment]
> 你好，我试着本地复现，但是没出现报错，如果你能提供一个最小复现仓库就好了

你好，我试着本地复现，但是没出现报错，如果你能提供一个最小复现仓库就好了
你好 尝试了最小复现仓库
https://stackblitz.com/edit/vitejs-vite-jydaqq?file=vite.config.js
我试着复现我的场景下的报错 但是monorepo项目有点复杂 但是复现了条件编译后找不到import资源的问题 应该是同一个问题引起的
image
使用--force 忽略缓存就可以复现 也就是为什么只有第一次才会出现报错

**Comment by kanfashidoufu** [comment]
> 你好，我试着本地复现，但是没出现报错，如果你能提供一个最小复现仓库就好了

你好 尝试了最小复现仓库
https://stackblitz.com/edit/vitejs-vite-jydaqq?file=vite.config.js
我试着复现我的场景下的报错 但是monorepo项目有点复杂 但是复现了条件编译后找不到import资源的问题 应该是同一个问题引起的
![image](https://github.com/KeJunMao/vite-plugin-conditional-compile/assets/24693561/40ca936b-b125-451b-9d61-a53e16cbd821)

使用--force 忽略缓存就可以复现 也就是为什么只有第一次才会出现报错

**Comment by KeJunMao** [comment]
当我配置了
```js
// vite.config.js

  resolve: {
    alias: {
      '@/': './',
    },
  },
```

并创建了 views/im/module/libs/util.js 文件后，使用 --force 启动依旧无法复现

```bash
~/projects/vitejs-vite-xuzxuq 12s
❯ pnpm install && pnpm run dev --force
Lockfile is up to date, resolution step is skipped
Already up to date
Done in 903ms

> vite-vue-starter@0.0.0 dev /home/projects/vitejs-vite-xuzxuq
> vite --mode development "--force"

Forced re-optimization of dependencies

  VITE v3.0.0  ready in 2181 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
```

**Comment by KeJunMao** [comment]
这个是你缺少下面的配置和对应的文件？我尝试创建文件并添加 alias 配置后，使用 --force 也是 ok 的呀
```ts
  resolve: {
    alias: {
      '@': 'src',
    },
  },
```

**Comment by kanfashidoufu** [comment]
> 这个是你缺少下面的配置和对应的文件？我尝试创建文件并添加 alias 配置后，使用 --force 也是 ok 的呀
> 
> ```ts
>   resolve: {
>     alias: {
>       '@': 'src',
>     },
>   },
> ```

是的 我发现了 我再尝试复现下

**Comment by KeJunMao** [comment]
暂时关闭了
